#!/data/data/com.termux/files/usr/bin/bash
# Redesigned Boot-kali-install.sh for Modern Magisk (v26+)
# Generated by NetHunter Script Architect
set -e

# --- Variable Definitions ---
FACTION="BEAR"
KALI_TEXT="┌──(root㉿kali)-[/]\n└─# "
THEME_NAME="/data/local/tmp/media/Boot-Animation-install.zip"
PREFIX_DIR="/data/data/com.termux/files/usr"
NH_PATH="/data/data/com.offsec.nhterm/files/usr/bin/kali"
CHROOT_DIR="/data/local/nhsystem/kalifs"

echo "[*] Starting Redesigned Boot-kali-install.sh for Faction: $FACTION"

# 1. Environment Validation
if [ ! -d "$PREFIX_DIR" ]; then
    echo "[!] Error: Termux environment not detected at $PREFIX_DIR"
    exit 1
fi

# 2. Dynamic Magisk Detection 
echo "[*] Detecting Magisk path..."
if [ -f "/debug_ramdisk/magisk" ]; then
    MAGISK="/debug_ramdisk/magisk"
elif [ -f "/sbin/magisk" ]; then
    MAGISK="/sbin/magisk"
else
    MAGISK="$(magisk --path)/magisk"
fi
echo "[+] Using Magisk at: $MAGISK"

# 3. Path Consistency Check 
# Fixes 'No such file or directory' by symlinking common chroot paths
if [ ! -L "$CHROOT_DIR" ] && [ -d "/data/local/nhsystem/kali-arm64" ]; then
    echo "[*] Symlinking kali-arm64 to kalifs for consistency..."
    $MAGISK su -c "ln -s /data/local/nhsystem/kali-arm64 $CHROOT_DIR"
fi

# 4. Deploy NH-Terminal Shim 
echo "[*] Patching NetHunter Terminal launcher..."
cat <<EOF >./kali_shim
#!/system/bin/sh
# Shim for modern Magisk chroot entry
$MAGISK su --mount-master -c "export LANG=en_US.UTF-8; /system/bin/chroot $CHROOT_DIR /bin/bash -l"
EOF

# Ensure LF line endings and proper permissions 
sed -i 's/\r$//' ./kali_shim
chmod 755 ./kali_shim
$MAGISK su -c "cp ./kali_shim $NH_PATH"
$MAGISK su -c "chmod 755 $NH_PATH"
rm ./kali_shim

# 5. Boot Animation Handling
if [ -f "$THEME_NAME" ]; then
    echo "[*] Verifying Boot Animation theme at $THEME_NAME..."
    $MAGISK su -c "chmod 644 $THEME_NAME"
else
    echo "[!] Warning: Theme zip not found at $THEME_NAME. Skipping theme config."
fi

# 6. Inject Prompt and Faction Identity 
echo "[*] Configuring Kali prompt and Faction: $FACTION..."
PROMPT_CMD="echo 'export PS1=\"$KALI_TEXT\"' >> /root/.bashrc"
$MAGISK su --mount-master -c "/system/bin/chroot $CHROOT_DIR /bin/bash -c \"$PROMPT_CMD\""
$MAGISK su --mount-master -c "/system/bin/chroot $CHROOT_DIR /bin/bash -c \"echo $FACTION > /etc/faction\""

echo "[+] Installation complete. Open NH-Terminal and select the Kali profile."
